name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
        run: docker build . --file Dockerfile --tag sbom_demo:$(date +%s)

      - name: Generate an SBOM for a Docker image
        uses: anchore/sbom-action@v0
        with:
          image: sbom_demo:$(date +%s)
